### ISSUE TITLE
[2024] Resources Page: Starter Pack Resources

### ISSUE THREAD

**Issue by waalbert** [HackAtUCI/zothacks-site#175]
After #170 and #171 are completed, and using the [Figma](https://www.figma.com/design/TiI2YA9E2FfF1hJwI9YT91/ZotHacks-2024-Website-Design?node-id=4-3&node-type=canvas&t=11JsQpIfpGJSuTVl-0), the Starter Pack Resources Section will need to be updated using the new shared Resources Section Title component and island components.

**Comment by IanWearsHat** [comment]
We should keep the full-stack starter pack.

The Docker and Angular starter packs do not exist, nor are they likely to be used in a beginner-oriented hackathon. These two should be replaced with the HTML/CSS/JS and Flask starter packs. 

HTML/CSS/JS pack: https://github.com/HackAtUCI/zothacks-frontend-startercode
Flask pack: https://github.com/HackAtUCI/zothacks-2020-backend
